spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: com
    username: sa
    password:

oauth:
  naver:
    client-id: test
    client-secret: test
    redirect-uri: test
  google:
    client-id: test
    client-secret: test
    redirect-uri: test
  kakao:
    client-id: test
    redirect-uri: test
    admin-key: test

aws:
  s3:
    bucket: test
    access-key: test
    secret-key: test
    region: ap-northeast-2

google:
  cloud:
    credentials:
      location: test
    project-id: test
    bucket-name: test

gemini:
  api-key: test

agora:
  appId: test
  appCert: test
  customerId: test
  customerSecret: test

security:
  oauth-token:
    secret: test
